import { StyleSheet, Dimensions, Platform } from 'react-native';
import { colors, spacing, typography } from '../theme';

const { width, height } = Dimensions.get('window');
export const cardWidth = (width - spacing.xl * 2 - spacing.md) / 2;

export const styles = StyleSheet.create({
    loadingContainer: {
        flex: 1,
        justifyContent: 'center',
        alignItems: 'center',
        backgroundColor: colors.background,
    },
    loadingText: {
        marginTop: spacing.md,
        fontSize: typography.fontSize.sm,
        color: colors.textSecondary,
        fontWeight: typography.fontWeight.bold,
    },
    container: {
        flex: 1,
        backgroundColor: '#fafafa', // Clean Apple/Ionic style background
    },
    header: {
        paddingTop: Platform.OS === 'ios' ? 50 : 30, // SafeArea
        paddingHorizontal: spacing.xl,
        paddingBottom: spacing.md,
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        borderBottomWidth: StyleSheet.hairlineWidth,
        borderBottomColor: 'rgba(255,255,255,0.3)',
        zIndex: 10,
    },
    headerTitle: {
        fontSize: typography.fontSize.xl,
        fontWeight: typography.fontWeight.black,
        color: colors.textPrimary,
        letterSpacing: -0.5,
    },
    headerActions: {
        flexDirection: 'row',
        gap: spacing.sm,
    },
    iconButton: {
        width: 40,
        height: 40,
        borderRadius: 20,
        backgroundColor: colors.white,
        justifyContent: 'center',
        alignItems: 'center',
        borderWidth: 1,
        borderColor: colors.border,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.03,
        shadowRadius: 5,
        elevation: 1,
        position: 'relative',
    },
    notificationBadge: {
        position: 'absolute',
        top: 8,
        right: 8,
        width: 10,
        height: 10,
        borderRadius: 5,
        backgroundColor: colors.error,
        borderWidth: 2,
        borderColor: colors.white,
    },
    iconButtonLogout: {
        width: 40,
        height: 40,
        borderRadius: 20,
        backgroundColor: 'rgba(239, 68, 68, 0.05)',
        justifyContent: 'center',
        alignItems: 'center',
        borderWidth: 1,
        borderColor: 'rgba(239, 68, 68, 0.2)',
    },
    modalOverlay: {
        flex: 1,
        backgroundColor: 'rgba(0,0,0,0.3)',
        justifyContent: 'flex-end',
    },
    notificationModal: {
        backgroundColor: colors.white,
        borderTopLeftRadius: 32,
        borderTopRightRadius: 32,
        paddingTop: spacing.xl,
        paddingHorizontal: spacing.xl,
        paddingBottom: Platform.OS === 'ios' ? 40 : 20,
        maxHeight: height * 0.7,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: -10 },
        shadowOpacity: 0.1,
        shadowRadius: 20,
        elevation: 10,
    },
    modalHeader: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        marginBottom: spacing.xl,
    },
    modalTitle: {
        fontSize: typography.fontSize.lg,
        fontWeight: typography.fontWeight.black,
        color: colors.textPrimary,
    },
    notificationsList: {
        marginBottom: spacing.md,
    },
    notificationItem: {
        flexDirection: 'row',
        paddingVertical: spacing.md,
        borderBottomWidth: 1,
        borderBottomColor: colors.border,
    },
    notifLead: {
        marginRight: spacing.md,
    },
    notifIconCircle: {
        width: 40,
        height: 40,
        borderRadius: 20,
        backgroundColor: colors.background,
        justifyContent: 'center',
        alignItems: 'center',
    },
    notifBody: {
        flex: 1,
    },
    notifTitle: {
        fontSize: typography.fontSize.sm,
        fontWeight: typography.fontWeight.bold,
        color: colors.textPrimary,
        marginBottom: 2,
    },
    notifMsg: {
        fontSize: typography.fontSize.xs,
        color: colors.textSecondary,
        marginBottom: 4,
    },
    notifTime: {
        fontSize: 10,
        color: colors.textMuted,
        fontWeight: typography.fontWeight.medium,
    },
    modalFooterButton: {
        backgroundColor: colors.background,
        paddingVertical: spacing.md,
        borderRadius: 16,
        alignItems: 'center',
        marginTop: spacing.sm,
    },
    modalFooterText: {
        fontSize: typography.fontSize.sm,
        fontWeight: typography.fontWeight.bold,
        color: colors.textPrimary,
    },
    scrollContent: {
        paddingVertical: spacing.xl,
        zIndex: 1,
    },
    greetingTitle: {
        fontSize: 12,
        fontWeight: typography.fontWeight.black,
        color: colors.textMuted,
        textTransform: 'uppercase',
        letterSpacing: 1.5,
        paddingHorizontal: spacing.xl,
        marginBottom: 4,
    },
    greetingSubtitle: {
        fontSize: typography.fontSize.xxl,
        fontWeight: typography.fontWeight.black,
        color: colors.textPrimary,
        paddingHorizontal: spacing.xl,
        letterSpacing: -1,
        marginBottom: spacing.xl,
    },
    content: {
        paddingHorizontal: spacing.xl,
        paddingBottom: spacing.xxl,
    },
    glassCardBase: {
        borderRadius: 24,
        padding: spacing.xl,
        marginBottom: spacing.md,
        backgroundColor: colors.white,
        borderWidth: 1,
        borderColor: colors.border,
        overflow: 'hidden',
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 4 },
        shadowOpacity: 0.03,
        shadowRadius: 10,
        elevation: 1,
    },
    cardHeaderRow: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        marginBottom: spacing.md,
    },
    glassIconContainerPrimary: {
        width: 52,
        height: 52,
        borderRadius: 16,
        backgroundColor: 'rgba(225, 29, 72, 0.1)',
        justifyContent: 'center',
        alignItems: 'center',
    },
    datePill: {
        paddingHorizontal: 12,
        paddingVertical: 6,
        backgroundColor: colors.background,
        borderRadius: 20,
        borderWidth: 1,
        borderColor: colors.border,
    },
    datePillText: {
        fontSize: 10,
        fontWeight: typography.fontWeight.black,
        color: colors.textSecondary,
        textTransform: 'uppercase',
    },
    cardLabel: {
        fontSize: typography.fontSize.xs,
        fontWeight: typography.fontWeight.black,
        color: colors.textSecondary,
        textTransform: 'uppercase',
        letterSpacing: 1.5,
        marginBottom: spacing.xs,
    },
    cardValue: {
        fontSize: 40,
        fontWeight: typography.fontWeight.black,
        color: colors.textPrimary,
        letterSpacing: -2,
    },
    cardSubtitle: {
        fontSize: typography.fontSize.xs,
        fontWeight: typography.fontWeight.bold,
        color: colors.textMuted,
        marginTop: spacing.xs,
    },
    statsGrid: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        marginBottom: spacing.lg,
    },
    glassCardGrid: {
        borderRadius: 20,
        padding: spacing.md,
        borderWidth: 1,
        borderColor: colors.border,
        backgroundColor: colors.white,
        flexDirection: 'column',
        justifyContent: 'space-between',
        height: 145,
        overflow: 'hidden',
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 4 },
        shadowOpacity: 0.03,
        shadowRadius: 10,
        elevation: 1,
    },
    glassIconContainerSecondary: {
        width: 40,
        height: 40,
        borderRadius: 12,
        backgroundColor: 'rgba(59, 130, 246, 0.1)',
        justifyContent: 'center',
        alignItems: 'center',
        marginBottom: spacing.sm,
    },
    glassIconContainerWarning: {
        width: 40,
        height: 40,
        borderRadius: 12,
        backgroundColor: 'rgba(245, 158, 11, 0.1)',
        justifyContent: 'center',
        alignItems: 'center',
        marginBottom: spacing.sm,
    },
    gridCardLabel: {
        fontSize: typography.fontSize.xs,
        fontWeight: typography.fontWeight.black,
        color: colors.textSecondary,
        textTransform: 'uppercase',
        letterSpacing: 1,
    },
    gridCardValue: {
        fontSize: typography.fontSize.xl,
        fontWeight: typography.fontWeight.black,
        color: colors.textPrimary,
        letterSpacing: -1,
    },
    gridCardSubtitle: {
        fontSize: 10,
        fontWeight: typography.fontWeight.bold,
        color: colors.textMuted,
    },
    badgeWarning: {
        backgroundColor: 'rgba(239, 68, 68, 0.1)',
        paddingHorizontal: 6,
        paddingVertical: 3,
        borderRadius: 6,
        alignSelf: 'flex-start',
        marginTop: 2,
    },
    badgeWarningText: {
        color: colors.error,
        fontSize: 8,
        fontWeight: typography.fontWeight.black,
        textTransform: 'uppercase',
        letterSpacing: 0.5,
    },
    glassSection: {
        borderRadius: 24,
        borderWidth: 1,
        borderColor: colors.border,
        backgroundColor: colors.white,
        overflow: 'hidden',
        marginBottom: spacing.lg,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 4 },
        shadowOpacity: 0.03,
        shadowRadius: 10,
        elevation: 1,
    },
    sectionHeader: {
        flexDirection: 'row',
        alignItems: 'center',
        padding: spacing.md,
        borderBottomWidth: 1,
        borderBottomColor: colors.border,
        backgroundColor: colors.white,
    },
    glassIconSmall: {
        width: 32,
        height: 32,
        borderRadius: 10,
        backgroundColor: colors.background,
        justifyContent: 'center',
        alignItems: 'center',
    },
    sectionTitle: {
        fontSize: typography.fontSize.sm,
        fontWeight: typography.fontWeight.black,
        color: colors.textPrimary,
        marginLeft: spacing.sm,
    },
    listContainer: {
        padding: spacing.md,
        gap: spacing.sm,
    },
    glassListItem: {
        flexDirection: 'row',
        alignItems: 'center',
        padding: spacing.sm,
        borderRadius: 16,
        backgroundColor: colors.white,
        borderWidth: 1,
        borderColor: colors.border,
    },
    listItemRank: {
        width: 36,
        height: 36,
        backgroundColor: 'rgba(0,0,0,0.03)',
        borderRadius: 10,
        justifyContent: 'center',
        alignItems: 'center',
        marginRight: spacing.md,
    },
    listItemRankText: {
        fontSize: typography.fontSize.base,
        fontWeight: typography.fontWeight.black,
        color: colors.textPrimary,
    },
    listItemInfo: {
        flex: 1,
    },
    listItemTitle: {
        fontSize: typography.fontSize.sm,
        fontWeight: typography.fontWeight.bold,
        color: colors.textPrimary,
    },
    listItemSubtitle: {
        fontSize: typography.fontSize.xs,
        fontWeight: typography.fontWeight.medium,
        color: colors.textMuted,
        marginTop: 2,
    },
    listItemRightBadge: {
        backgroundColor: 'rgba(225, 29, 72, 0.1)',
        paddingHorizontal: 12,
        paddingVertical: 6,
        borderRadius: 20,
    },
    listItemRightBadgeText: {
        fontSize: typography.fontSize.xs,
        fontWeight: typography.fontWeight.black,
        color: colors.primary,
    },
    emptyText: {
        padding: spacing.xl,
        textAlign: 'center',
        color: colors.textMuted,
        fontWeight: typography.fontWeight.medium,
        fontSize: typography.fontSize.sm,
    }
});
