import { StyleSheet, Dimensions, Platform } from 'react-native';

const { width } = Dimensions.get('window');

export const createModalStyles = (colors: any) => StyleSheet.create({
    modalOverlay: {
        flex: 1,
        backgroundColor: colors.background,
    },
    modalContent: {
        flex: 1,
        backgroundColor: colors.background,
        overflow: 'hidden',
    },
    header: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        paddingHorizontal: 24,
        paddingTop: Platform.OS === 'ios' ? 60 : 24,
        paddingBottom: 16,
    },
    headerTitleBox: {
        flex: 1,
    },
    headerPrefix: {
        fontSize: 12,
        fontWeight: '900',
        color: colors.primary,
        textTransform: 'uppercase',
        letterSpacing: 2,
        marginBottom: 2,
    },
    headerTitle: {
        fontSize: 28,
        fontWeight: '900',
        color: colors.textPrimary,
        letterSpacing: -0.5,
    },
    closeButton: {
        width: 44,
        height: 44,
        borderRadius: 22,
        backgroundColor: colors.surface,
        justifyContent: 'center',
        alignItems: 'center',
        borderWidth: 1,
        borderColor: colors.border,
    },
    scrollContent: {
        paddingHorizontal: 24,
        paddingBottom: 120,
    },
    keyboardView: {
        flex: 1,
    },

    // Image Upload
    imageWrapper: {
        alignItems: 'center',
        marginBottom: 32,
    },
    imageCircle: {
        width: 140,
        height: 140,
        borderRadius: 70,
        backgroundColor: colors.surface,
        justifyContent: 'center',
        alignItems: 'center',
        borderWidth: 1.5,
        borderColor: colors.border,
        overflow: 'hidden',
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 10 },
        shadowOpacity: 0.1,
        shadowRadius: 20,
        elevation: 8,
    },
    imagePreview: {
        width: '100%',
        height: '100%',
        resizeMode: 'cover',
    },
    imageBadge: {
        position: 'absolute',
        bottom: 0,
        backgroundColor: colors.primary,
        paddingHorizontal: 12,
        paddingVertical: 6,
        borderRadius: 12,
    },
    imageBadgeText: {
        color: '#fff',
        fontSize: 10,
        fontWeight: '900',
    },

    // Caitlyn Card (Top)
    caitlynCard: {
        backgroundColor: colors.surface,
        borderRadius: 24,
        padding: 20,
        marginBottom: 24,
        borderWidth: 1,
        borderColor: colors.primary + '20',
        shadowColor: colors.primary,
        shadowOffset: { width: 0, height: 8 },
        shadowOpacity: 0.1,
        shadowRadius: 12,
        elevation: 5,
    },
    caitlynHeader: {
        flexDirection: 'row',
        alignItems: 'center',
        marginBottom: 16,
    },
    caitlynIconCircle: {
        width: 44,
        height: 44,
        borderRadius: 22,
        backgroundColor: colors.primary,
        justifyContent: 'center',
        alignItems: 'center',
        marginRight: 14,
    },
    caitlynHeaderText: {
        flex: 1,
    },
    caitlynTitle: {
        fontSize: 16,
        fontWeight: '900',
        color: colors.textPrimary,
    },
    caitlynSub: {
        fontSize: 12,
        fontWeight: '700',
        color: colors.textMuted,
    },
    caitlynPromptBox: {
        backgroundColor: colors.background,
        borderRadius: 16,
        padding: 12,
        borderWidth: 1,
        borderColor: colors.border,
    },
    caitlynInputRow: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 12,
    },
    caitlynInput: {
        flex: 1,
        height: 44,
        fontSize: 15,
        fontWeight: '700',
        color: colors.textPrimary,
    },
    caitlynActionBtn: {
        backgroundColor: colors.primary,
        paddingHorizontal: 16,
        height: 44,
        borderRadius: 12,
        justifyContent: 'center',
        alignItems: 'center',
    },
    applySuggestionBtn: {
        backgroundColor: colors.primary,
        paddingHorizontal: 12,
        paddingVertical: 6,
        borderRadius: 10,
    },
    applySuggestionText: {
        color: '#fff',
        fontSize: 12,
        fontWeight: '900',
    },
    caitlynInsightBox: {
        flexDirection: 'row',
        backgroundColor: colors.primary + '11',
        padding: 16,
        borderRadius: 16,
        marginBottom: 16,
        borderWidth: 1,
        borderColor: colors.primary + '22',
    },
    caitlynInsightText: {
        flex: 1,
        fontSize: 13,
        fontWeight: '600',
        color: colors.textPrimary,
        lineHeight: 18,
    },
    sugerenciaPreviewBox: {
        backgroundColor: colors.surface,
        borderRadius: 16,
        padding: 16,
        marginBottom: 16,
        borderWidth: 1,
        borderColor: colors.border,
        borderStyle: 'dashed',
    },
    sugerenciaTitle: {
        fontSize: 11,
        fontWeight: '900',
        color: colors.primary,
        marginBottom: 12,
        letterSpacing: 1,
    },
    sugerenciaList: {
        marginBottom: 16,
    },
    sugerenciaItem: {
        fontSize: 13,
        color: colors.textSecondary,
        marginBottom: 4,
    },
    applyRecipeBtn: {
        flexDirection: 'row',
        backgroundColor: colors.primary,
        paddingVertical: 12,
        borderRadius: 12,
        justifyContent: 'center',
        alignItems: 'center',
    },
    applyRecipeText: {
        color: '#fff',
        fontSize: 13,
        fontWeight: 'bold',
    },
    caitlynSuggestBtn: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 10,
        backgroundColor: colors.primary + '11',
        padding: 16,
        borderRadius: 16,
        justifyContent: 'center',
    },
    caitlynSuggestText: {
        color: colors.primary,
        fontWeight: '900',
        fontSize: 14,
    },

    // Form Layout
    inputLabel: {
        fontSize: 11,
        fontWeight: '900',
        color: colors.textSecondary,
        textTransform: 'uppercase',
        letterSpacing: 1.5,
        marginBottom: 10,
        marginLeft: 4,
    },
    mainInput: {
        backgroundColor: colors.surface,
        borderRadius: 18,
        paddingHorizontal: 20,
        paddingVertical: 16,
        fontSize: 17,
        fontWeight: '800',
        color: colors.textPrimary,
        borderWidth: 1.5,
        borderColor: colors.border,
        marginBottom: 20,
    },
    descriptionInput: {
        height: 100,
        textAlignVertical: 'top',
    },
    row: {
        flexDirection: 'row',
        gap: 16,
        marginBottom: 20,
    },
    col: {
        flex: 1,
    },

    // Category Selector (Icon-driven)
    categoryGrid: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        backgroundColor: colors.surface,
        borderRadius: 20,
        padding: 6,
        borderWidth: 1.5,
        borderColor: colors.border,
    },
    categoryItem: {
        flex: 1,
        height: 48,
        borderRadius: 14,
        justifyContent: 'center',
        alignItems: 'center',
    },
    categoryItemActive: {
        backgroundColor: colors.primary,
        shadowColor: colors.primary,
        shadowOffset: { width: 0, height: 4 },
        shadowOpacity: 0.3,
        shadowRadius: 8,
        elevation: 4,
    },

    // Visibility Toggle
    toggleCard: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        backgroundColor: colors.surface,
        borderRadius: 20,
        padding: 16,
        paddingRight: 10,
        marginBottom: 24,
        borderWidth: 1,
        borderColor: colors.border,
    },
    toggleInfo: {
        flex: 1,
    },
    toggleLabel: {
        fontSize: 15,
        fontWeight: '900',
        color: colors.textPrimary,
    },
    toggleSub: {
        fontSize: 11,
        fontWeight: '700',
        color: colors.textMuted,
        textTransform: 'uppercase',
        marginTop: 2,
    },

    // Recipe Section
    recipeHeader: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        marginBottom: 16,
        marginTop: 8,
    },
    recipeTitle: {
        fontSize: 18,
        fontWeight: '900',
        color: colors.textPrimary,
    },
    addBtn: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 6,
        backgroundColor: colors.primary + '15',
        paddingHorizontal: 12,
        paddingVertical: 8,
        borderRadius: 12,
    },
    addBtnText: {
        color: colors.primary,
        fontSize: 13,
        fontWeight: '900',
    },
    recipeContainer: {
        backgroundColor: colors.surface,
        borderRadius: 24,
        borderWidth: 1,
        borderColor: colors.border,
        overflow: 'hidden',
        marginBottom: 40,
    },
    ingredientRow: {
        flexDirection: 'row',
        alignItems: 'center',
        padding: 16,
        backgroundColor: colors.surface,
    },
    ingredientSeparator: {
        height: 1,
        backgroundColor: colors.border,
        marginHorizontal: 16,
    },
    statusIconBox: {
        width: 32,
        alignItems: 'flex-start',
    },
    deleteAction: {
        backgroundColor: '#e11d48',
        width: 80,
        height: '100%',
        justifyContent: 'center',
        alignItems: 'center',
    },
    ingredientInfo: {
        flex: 1,
    },
    ingredientName: {
        fontSize: 16,
        fontWeight: '900',
        color: colors.textPrimary,
    },
    qtyUnitRow: {
        flexDirection: 'row',
        alignItems: 'center',
        marginTop: 4,
        backgroundColor: colors.background,
        alignSelf: 'flex-start',
        paddingHorizontal: 8,
        paddingVertical: 5,
        borderRadius: 10,
        borderWidth: 1,
        borderColor: colors.border,
    },
    qtyInput: {
        fontSize: 14,
        fontWeight: '900',
        color: colors.textPrimary,
        padding: 0,
        margin: 0,
        width: 25,
        textAlign: 'right',
        marginRight: 4,
    },
    unitLabel: {
        fontSize: 12,
        fontWeight: '900',
        color: colors.textMuted,
        textTransform: 'lowercase',
    },

    // Footer
    footer: {
        position: 'absolute',
        bottom: 0,
        left: 0,
        right: 0,
        backgroundColor: colors.background,
        padding: 24,
        paddingBottom: Platform.OS === 'ios' ? 40 : 24,
        borderTopWidth: 1,
        borderTopColor: colors.border,
        flexDirection: 'row',
        gap: 12,
    },
    btnSubmit: {
        flex: 1,
        height: 58,
        backgroundColor: colors.primary,
        borderRadius: 20,
        justifyContent: 'center',
        alignItems: 'center',
        shadowColor: colors.primary,
        shadowOffset: { width: 0, height: 6 },
        shadowOpacity: 0.3,
        shadowRadius: 10,
        elevation: 6,
    },
    btnSubmitText: {
        fontSize: 16,
        fontWeight: '900',
        color: '#fff',
        textTransform: 'uppercase',
        letterSpacing: 1.5,
    },
    btnCancel: {
        width: 58,
        height: 58,
        backgroundColor: colors.surface,
        borderRadius: 20,
        justifyContent: 'center',
        alignItems: 'center',
        borderWidth: 1.5,
        borderColor: colors.border,
    },
});
