import { StyleSheet, Dimensions } from 'react-native';

const { width } = Dimensions.get('window');

export const styles = StyleSheet.create({
    container: {
        flex: 1,
    },
    headerRow: {
        flexDirection: 'row',
        alignItems: 'center',
        paddingHorizontal: 16,
        marginTop: 16,
        marginBottom: 8,
        gap: 12,
    },
    searchInputWrapper: {
        flex: 1,
        flexDirection: 'row',
        alignItems: 'center',
        borderWidth: 1,
        borderRadius: 16,
        paddingHorizontal: 14,
        paddingVertical: 12,
    },
    searchInput: {
        flex: 1,
        marginLeft: 10,
        marginRight: 10,
        fontSize: 16,
        fontWeight: '600',
    },
    filterContainer: {
        height: 50,
        marginBottom: 16,
    },
    filterScrollView: {
        paddingHorizontal: 16,
        height: 50,
        flexGrow: 0,
    },
    filterPill: {
        flexDirection: 'row',
        paddingHorizontal: 20,
        height: 38,
        borderRadius: 20,
        justifyContent: 'center',
        alignItems: 'center',
        marginRight: 10,
        borderWidth: 1,
        alignSelf: 'center',
    },
    filterText: {
        fontSize: 14,
        fontWeight: 'bold',
        textTransform: 'capitalize',
    },
    listContainer: {
        paddingHorizontal: 16,
        paddingBottom: 100,
    },
    itemCard: {
        flexDirection: 'row',
        alignItems: 'center',
        paddingVertical: 12,
        paddingHorizontal: 16,
        borderBottomWidth: StyleSheet.hairlineWidth,
    },
    itemIconBox: {
        width: 48,
        height: 48,
        borderRadius: 14,
        justifyContent: 'center',
        alignItems: 'center',
        marginRight: 16,
        overflow: 'hidden',
    },
    productImage: {
        width: '100%',
        height: '100%',
        resizeMode: 'cover',
    },
    emojiText: {
        fontSize: 24,
    },
    itemInfo: {
        flex: 1,
        marginRight: 8,
    },
    itemTitleRow: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'flex-start',
        marginBottom: 4,
    },
    itemTitle: {
        fontSize: 16,
        fontWeight: '900',
        flex: 1,
    },
    itemPrice: {
        fontSize: 16,
        fontWeight: '900',
        marginLeft: 8,
    },
    itemSub: {
        fontSize: 12,
        fontWeight: '700',
        textTransform: 'uppercase',
        letterSpacing: 1,
    },
    itemStatus: {
        paddingHorizontal: 8,
        paddingVertical: 2,
        borderRadius: 12,
        alignSelf: 'flex-start',
        marginTop: 4,
    },
    itemStatusText: {
        fontSize: 9,
        fontWeight: '900',
        textTransform: 'uppercase',
        letterSpacing: 1,
    },
    fabRow: {
        position: 'absolute',
        bottom: 24,
        right: 24,
        gap: 12,
    },
    fab: {
        width: 56,
        height: 56,
        borderRadius: 28,
        justifyContent: 'center',
        alignItems: 'center',
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 4 },
        shadowOpacity: 0.2,
        shadowRadius: 8,
        elevation: 6,
    },
    secFab: {
        width: 56,
        height: 56,
        borderRadius: 28,
        justifyContent: 'center',
        alignItems: 'center',
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 4 },
        shadowOpacity: 0.2,
        shadowRadius: 8,
        elevation: 4,
        alignSelf: 'flex-end',
    },
    emptyState: {
        paddingVertical: 60,
        alignItems: 'center',
        justifyContent: 'center',
        paddingHorizontal: 32,
    },
    emptyIconBox: {
        width: 80,
        height: 80,
        borderRadius: 40,
        justifyContent: 'center',
        alignItems: 'center',
        marginBottom: 16,
    },
    emptyTitle: {
        fontSize: 20,
        fontWeight: '900',
        marginBottom: 8,
    },
    emptySub: {
        fontSize: 14,
        fontWeight: '500',
        textAlign: 'center',
        marginBottom: 24,
        lineHeight: 20,
    },
    modalOverlay: {
        flex: 1,
        justifyContent: 'flex-end',
        margin: 0,
    },
    modalContent: {
        width: '100%',
        height: '92%',
        borderTopLeftRadius: 32,
        borderTopRightRadius: 32,
        overflow: 'hidden',
    },
    modalHeader: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        paddingHorizontal: 24,
        paddingTop: 24,
        paddingBottom: 16,
    },
    modalTitle: {
        fontSize: 24,
        fontWeight: '900',
        fontStyle: 'italic',
        letterSpacing: -0.5,
    },
    closeButton: {
        width: 40,
        height: 40,
        borderRadius: 20,
        justifyContent: 'center',
        alignItems: 'center',
    },
    formContainer: {
        paddingHorizontal: 24,
        paddingBottom: 40,
        gap: 20,
    },
    formRow: {
        flexDirection: 'row',
        gap: 16,
    },
    flex1: {
        flex: 1,
    },
    imageUploadContainer: {
        alignItems: 'center',
        marginBottom: 8,
    },
    imageUploadBox: {
        width: 140,
        height: 140,
        borderRadius: 40,
        borderWidth: 2,
        borderStyle: 'dashed',
        justifyContent: 'center',
        alignItems: 'center',
        overflow: 'hidden',
    },
    imageUploadText: {
        fontSize: 10,
        fontWeight: '900',
        textTransform: 'uppercase',
        letterSpacing: 1,
        textAlign: 'center',
        marginTop: 8,
    },
    deleteImageBtn: {
        position: 'absolute',
        top: -4,
        right: -4,
        width: 32,
        height: 32,
        borderRadius: 16,
        justifyContent: 'center',
        alignItems: 'center',
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.1,
        shadowRadius: 4,
        elevation: 2,
    },
    toggleRow: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        padding: 16,
        borderWidth: 1,
        borderRadius: 16,
    },
    toggleTitle: {
        fontSize: 14,
        fontWeight: '900',
    },
    toggleSub: {
        fontSize: 10,
        fontWeight: '700',
        textTransform: 'uppercase',
        letterSpacing: 1,
        marginTop: 2,
    },
    sectionTitleRow: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        marginTop: 16,
        marginBottom: 12,
        borderTopWidth: 1,
        paddingTop: 20,
    },
    sectionTitle: {
        fontSize: 14,
        fontWeight: '900',
    },
    addIngredientBtn: {
        flexDirection: 'row',
        alignItems: 'center',
        paddingHorizontal: 12,
        paddingVertical: 6,
        borderRadius: 12,
        gap: 4,
    },
    addIngredientText: {
        fontSize: 12,
        fontWeight: '900',
    },
    ingredientRow: {
        flexDirection: 'row',
        alignItems: 'center',
        padding: 8,
        borderRadius: 16,
        borderWidth: 1,
        marginBottom: 12,
        gap: 8,
    },
    ingredientSelect: {
        flex: 2,
        height: 44,
        justifyContent: 'center',
        paddingHorizontal: 12,
        borderWidth: 1,
        borderRadius: 12,
    },
    ingredientInput: {
        flex: 1,
        height: 44,
        borderWidth: 1,
        borderRadius: 12,
        paddingHorizontal: 8,
        textAlign: 'center',
        fontWeight: '700',
        fontSize: 14,
    },
    deleteIngredientBtn: {
        width: 36,
        height: 36,
        borderRadius: 10,
        justifyContent: 'center',
        alignItems: 'center',
    },
});
