import { StyleSheet, Platform } from 'react-native';
import { spacing, typography } from '../theme';

export const createStyles = (colors: any, width: number, height: number) => {
    const isTablet = width > 768;
    const isLandscape = width > height;

    return StyleSheet.create({
        container: {
            flex: 1,
            backgroundColor: colors.background,
        },
        header: {
            paddingTop: Platform.OS === 'ios' ? 60 : (isLandscape ? 8 : 40),
            paddingHorizontal: isTablet ? spacing.xxl : spacing.xl,
            paddingBottom: isLandscape ? 2 : spacing.md,
            flexDirection: 'row',
            justifyContent: 'space-between',
            alignItems: 'center',
            height: isLandscape ? 50 : undefined, // Altura fija en landscape
        },
        headerTitle: {
            fontFamily: typography.fontFamily.black,
            fontSize: isLandscape ? 18 : (isTablet ? 28 : 22),
            fontWeight: typography.fontWeight.black,
            color: colors.textPrimary,
            letterSpacing: -0.5,
        },
        cartButton: {
            width: isLandscape ? 34 : 44,
            height: isLandscape ? 34 : 44,
            borderRadius: 10,
            backgroundColor: colors.white,
            justifyContent: 'center',
            alignItems: 'center',
            borderWidth: 1,
            borderColor: colors.border,
            position: 'relative',
        },
        cartBadge: {
            position: 'absolute',
            top: -4,
            right: -4,
            minWidth: 16,
            height: 16,
            borderRadius: 8,
            backgroundColor: colors.primary,
            justifyContent: 'center',
            alignItems: 'center',
            borderWidth: 1.5,
            borderColor: colors.white,
        },
        cartBadgeText: {
            fontFamily: typography.fontFamily.black,
            color: colors.white,
            fontSize: 8,
            fontWeight: typography.fontWeight.black,
        },
        searchContainer: {
            paddingHorizontal: isTablet ? spacing.xxl : spacing.xl,
            marginBottom: isLandscape ? 4 : spacing.md,
        },
        searchInputWrapper: {
            flexDirection: 'row',
            alignItems: 'center',
            backgroundColor: colors.white,
            borderRadius: 12,
            paddingHorizontal: spacing.md,
            height: isLandscape ? 36 : 52,
            borderWidth: 1,
            borderColor: colors.border,
        },
        searchInput: {
            fontFamily: typography.fontFamily.medium,
            flex: 1,
            marginLeft: spacing.sm,
            fontSize: isLandscape ? 12 : typography.fontSize.sm,
            fontWeight: typography.fontWeight.bold,
            color: colors.textPrimary,
        },
        categoriesContainer: {
            paddingHorizontal: isTablet ? spacing.xxl : spacing.xl,
            flexDirection: 'row',
            gap: 8,
            marginBottom: isLandscape ? 6 : spacing.lg,
        },
        categoryChip: {
            paddingVertical: isLandscape ? 4 : 10,
            paddingHorizontal: isLandscape ? 10 : 16,
            borderRadius: 12,
            borderWidth: 1.5,
            borderColor: colors.border,
            backgroundColor: colors.white,
            justifyContent: 'center',
            alignItems: 'center',
        },
        categoryChipActive: {
            backgroundColor: colors.primary,
            borderColor: colors.primary,
        },
        categoryText: {
            fontFamily: typography.fontFamily.black,
            fontSize: isLandscape ? 9 : 11,
            fontWeight: typography.fontWeight.black,
            color: colors.textSecondary,
            textTransform: 'uppercase',
            letterSpacing: 0.5,
        },
        categoryTextActive: {
            color: colors.white,
        },
        productsGrid: {
            paddingHorizontal: isTablet ? spacing.xxl : spacing.xl,
            paddingTop: isLandscape ? 4 : 20,
            flexDirection: 'row',
            flexWrap: 'wrap',
            justifyContent: 'flex-start',
            gap: isLandscape ? 12 : 16,
            paddingBottom: 100,
        },
        productCard: {
            width: isTablet 
                ? (width - (isTablet ? spacing.xxl * 2 : spacing.xl * 2) - (isLandscape ? 48 : 48)) / (isLandscape ? 5 : 4) 
                : (width - (spacing.xl * 2) - 16) / 2,
            backgroundColor: colors.white,
            borderRadius: 20,
            padding: isLandscape ? 8 : 12,
            marginBottom: isLandscape ? 8 : 4,
            borderWidth: 1,
            borderColor: colors.border,
            position: 'relative',
        },
    stockBadge: {
        position: 'absolute',
        top: 8,
        right: 8,
        zIndex: 10,
        backgroundColor: '#ef4444',
        paddingHorizontal: 6,
        paddingVertical: 2,
        borderRadius: 6,
    },
    stockBadgeText: {
        color: 'white',
        fontSize: 8,
        fontWeight: 'bold',
        textTransform: 'uppercase',
    },
    imagePlaceholder: {
        aspectRatio: 1,
        backgroundColor: colors.background,
        borderRadius: 18,
        justifyContent: 'center',
        alignItems: 'center',
        marginBottom: 10,
    },
    productInfo: {
        flex: 1,
    },
    productName: {
        fontFamily: typography.fontFamily.medium,
        fontSize: isTablet ? 14 : 12.5,
        fontWeight: typography.fontWeight.bold,
        color: colors.textPrimary,
        height: isTablet ? 32 : 30,
    },
    faltantesText: {
        color: '#ef4444',
        fontSize: 8,
        marginTop: 2,
        fontWeight: '700',
    },
    productPrice: {
        fontFamily: typography.fontFamily.bold,
        fontSize: isTablet ? 16 : 14,
        fontWeight: '900',
        color: colors.primary,
        marginTop: 4,
    },
    emptyContainer: {
        paddingTop: 60,
        alignItems: 'center',
        justifyContent: 'center',
    },
    emptyText: {
        fontFamily: typography.fontFamily.medium,
        marginTop: 10,
        fontSize: typography.fontSize.sm,
        fontWeight: typography.fontWeight.bold,
        color: colors.textMuted,
    },
    // Modal Styles
    modalOverlay: {
        flex: 1,
        backgroundColor: 'rgba(0,0,0,0.4)',
        justifyContent: 'flex-end',
    },
    modalContent: {
        backgroundColor: colors.white,
        borderTopLeftRadius: 32,
        borderTopRightRadius: 32,
        height: '85%',
        paddingTop: spacing.xl,
    },
    modalHeader: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        paddingHorizontal: spacing.xl,
        marginBottom: spacing.lg,
    },
    modalTitle: {
        fontFamily: typography.fontFamily.black,
        fontSize: typography.fontSize.xl,
        fontWeight: typography.fontWeight.black,
        color: colors.textPrimary,
    },
    modalSubtitle: {
        fontFamily: typography.fontFamily.black,
        fontSize: 10,
        fontWeight: typography.fontWeight.black,
        color: colors.textMuted,
        textTransform: 'uppercase',
        letterSpacing: 1.5,
    },
    carritoList: {
        paddingHorizontal: 20,
        paddingBottom: 40,
    },
    cartItem: {
        flexDirection: 'row',
        alignItems: 'center',
        backgroundColor: colors.surface,
        padding: 16,
        borderRadius: 24,
        marginBottom: 14,
        borderWidth: 1.5,
        borderColor: colors.border + '44',
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 4 },
        shadowOpacity: 0.05,
        shadowRadius: 10,
        elevation: 2,
    },
    cartItemImage: {
        width: 54,
        height: 54,
        borderRadius: 16,
        backgroundColor: colors.background,
        justifyContent: 'center',
        alignItems: 'center',
        marginRight: 14,
    },
    cartItemInfo: {
        flex: 1,
    },
    cartItemName: {
        fontSize: isTablet ? 15 : 13.5,
        fontWeight: '900',
        color: colors.textPrimary,
        letterSpacing: -0.3,
    },
    cartItemPrice: {
        fontSize: 13,
        fontWeight: '700',
        color: colors.primary,
        marginTop: 2,
    },
    quantityControls: {
        flexDirection: 'row',
        alignItems: 'center',
        backgroundColor: colors.background,
        borderRadius: 20,
        padding: 4,
        borderWidth: 1,
        borderColor: colors.border,
    },
    qtyBtn: {
        width: 32,
        height: 32,
        borderRadius: 16,
        backgroundColor: colors.surface,
        justifyContent: 'center',
        alignItems: 'center',
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.1,
        shadowRadius: 4,
        elevation: 2,
    },
    qtyText: {
        width: 30,
        textAlign: 'center',
        fontSize: 14,
        fontWeight: '900',
        color: colors.textPrimary,
    },
    checkoutFooter: {
        padding: 24,
        backgroundColor: colors.surface,
        borderTopLeftRadius: 32,
        borderTopRightRadius: 32,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: -10 },
        shadowOpacity: 0.05,
        shadowRadius: 15,
        elevation: 20,
        paddingBottom: Platform.OS === 'ios' ? 40 : 24,
    },
    formRow: {
        flexDirection: 'row',
        gap: 12,
        marginBottom: 24,
    },
    inputSmall: {
        flex: 1.5,
        backgroundColor: colors.background,
        borderRadius: 16,
        paddingHorizontal: 16,
        height: 52,
        borderWidth: 1.5,
        borderColor: colors.border,
        fontSize: 14,
        fontWeight: '700',
        color: colors.textPrimary,
    },
    selectSmall: {
        flex: 1,
        backgroundColor: colors.background,
        borderRadius: 16,
        justifyContent: 'center',
        paddingHorizontal: 12,
        height: 52,
        borderWidth: 1.5,
        borderColor: colors.border,
    },
    selectText: {
        fontSize: 13,
        fontWeight: '900',
        color: colors.textPrimary,
        textAlign: 'center',
    },
    totalRow: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'flex-end',
        marginBottom: 24,
    },
    totalLabel: {
        fontSize: 12,
        fontWeight: '900',
        color: colors.textMuted,
        textTransform: 'uppercase',
        letterSpacing: 1,
    },
    totalValue: {
        fontSize: 38,
        fontWeight: '900',
        color: colors.textPrimary,
        letterSpacing: -1.5,
    },
    confirmBtn: {
        backgroundColor: colors.primary,
        height: 64,
        borderRadius: 22,
        flexDirection: 'row',
        justifyContent: 'center',
        alignItems: 'center',
        gap: 10,
        shadowColor: colors.primary,
        shadowOffset: { width: 0, height: 8 },
        shadowOpacity: 0.3,
        shadowRadius: 15,
        elevation: 8,
    },
    confirmBtnText: {
        color: colors.white,
        fontSize: 18,
        fontWeight: '900',
    },
    metodoTag: {
        paddingVertical: 8,
        paddingHorizontal: 12,
        borderRadius: 12,
        borderWidth: 1,
        borderColor: colors.border,
        backgroundColor: colors.surface,
    },
    metodoTagText: {
        fontSize: 16,
        fontWeight: 'bold',
    },
    // Sidebar Styles (Tablet/Landscape)
    sidebar: {
        width: 280,
        height: '100%',
        borderRightWidth: 1,
        borderColor: colors.border,
        padding: 20,
        backgroundColor: colors.card,
    },
    sidebarHeader: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        marginBottom: 20,
        paddingTop: 10,
    },
    sidebarTitle: {
        fontSize: 22,
        fontWeight: '900',
        color: colors.textPrimary,
    },
    addBtn: {
        width: 36,
        height: 36,
        borderRadius: 12,
        backgroundColor: colors.primary,
        justifyContent: 'center',
        alignItems: 'center',
    },
    orderItem: {
        flexDirection: 'row',
        alignItems: 'center',
        padding: 12,
        borderRadius: 16,
        marginBottom: 8,
        borderWidth: 1,
        borderColor: 'transparent',
    },
    orderIcon: {
        width: 32,
        height: 32,
        borderRadius: 10,
        backgroundColor: colors.surface,
        justifyContent: 'center',
        alignItems: 'center',
        marginRight: 12,
    },
    orderName: {
        fontSize: 14,
        fontWeight: '800',
        color: colors.textPrimary,
    },
    orderMeta: {
        fontSize: 11,
        fontWeight: '600',
        color: colors.textMuted,
    },
    activeDot: {
        width: 6,
        height: 6,
        borderRadius: 3,
        marginLeft: 8,
        backgroundColor: colors.primary,
    },
    sidebarFooter: {
        marginTop: 'auto',
        paddingTop: 20,
        borderTopWidth: 1,
        borderColor: colors.border,
    },
    historyBtn: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 10,
        padding: 14,
        borderRadius: 14,
        backgroundColor: colors.surface,
    },
    historyText: {
        fontSize: 14,
        fontWeight: '800',
        color: colors.textPrimary,
    },
    scanBtn: {
        marginBottom: 10,
        borderWidth: 1,
        borderColor: colors.primary,
    },
    successOverlay: {
        position: 'absolute',
        top: Platform.OS === 'ios' ? 70 : (isLandscape ? 20 : 60),
        alignSelf: 'center',
        flexDirection: 'row',
        backgroundColor: colors.primary,
        paddingHorizontal: 20,
        paddingVertical: 12,
        borderRadius: 100,
        justifyContent: 'center',
        alignItems: 'center',
        gap: 10,
        zIndex: 9999,
        shadowColor: colors.primary,
        shadowOffset: { width: 0, height: 6 },
        shadowOpacity: 0.4,
        shadowRadius: 15,
        elevation: 10,
    },
    successCircle: {
        backgroundColor: 'rgba(255,255,255,0.2)',
        borderRadius: 16,
        padding: 4,
        justifyContent: 'center',
        alignItems: 'center',
    },
    fab: {
        position: 'absolute',
        bottom: 30,
        right: 30,
        width: 60,
        height: 60,
        borderRadius: 30,
        backgroundColor: colors.primary,
        justifyContent: 'center',
        alignItems: 'center',
        elevation: 8,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 4 },
        shadowOpacity: 0.3,
        shadowRadius: 8,
    },
    // Analysis Overlay Styles
    analysisOverlay: {
        ...StyleSheet.absoluteFillObject,
        backgroundColor: 'rgba(0,0,0,0.92)',
        justifyContent: 'center',
        alignItems: 'center',
        zIndex: 10000,
    },
    analysisContent: {
        alignItems: 'center',
        padding: 30,
        width: '100%',
    },
    analysisIconContainer: {
        width: 90,
        height: 90,
        borderRadius: 45,
        backgroundColor: colors.primary,
        justifyContent: 'center',
        alignItems: 'center',
        marginBottom: 24,
        shadowColor: colors.primary,
        shadowOffset: { width: 0, height: 15 },
        shadowOpacity: 0.6,
        shadowRadius: 25,
        elevation: 20,
    },
    analysisTitle: {
        fontSize: 24,
        fontWeight: '900',
        color: '#fff',
        marginBottom: 12,
        textAlign: 'center',
    },
    analysisSubtitle: {
        fontSize: 15,
        color: 'rgba(255,255,255,0.7)',
        textAlign: 'center',
        maxWidth: 280,
        lineHeight: 22,
        fontWeight: '600',
    },
    });
};
