import { StyleSheet, Dimensions, Platform } from 'react-native';
import { colors, spacing, borderRadius, typography } from '../theme';

const { width, height } = Dimensions.get('window');

export const styles = StyleSheet.create({
    container: {
        flex: 1,
        backgroundColor: colors.background,
    },
    header: {
        paddingTop: Platform.OS === 'ios' ? 60 : 40,
        paddingHorizontal: spacing.xl,
        paddingBottom: spacing.md,
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
    },
    headerTitle: {
        fontFamily: typography.fontFamily.black,
        fontSize: typography.fontSize.xl,
        fontWeight: typography.fontWeight.black,
        color: colors.textPrimary,
        letterSpacing: -0.5,
    },
    cartButton: {
        width: 44,
        height: 44,
        borderRadius: 14,
        backgroundColor: colors.white,
        justifyContent: 'center',
        alignItems: 'center',
        borderWidth: 1,
        borderColor: colors.border,
        position: 'relative',
    },
    cartBadge: {
        position: 'absolute',
        top: -5,
        right: -5,
        minWidth: 20,
        height: 20,
        borderRadius: 10,
        backgroundColor: colors.primary,
        justifyContent: 'center',
        alignItems: 'center',
        borderWidth: 2,
        borderColor: colors.white,
    },
    cartBadgeText: {
        fontFamily: typography.fontFamily.black,
        color: colors.white,
        fontSize: 10,
        fontWeight: typography.fontWeight.black,
    },
    searchContainer: {
        paddingHorizontal: spacing.xl,
        marginBottom: spacing.md,
    },
    searchInputWrapper: {
        flexDirection: 'row',
        alignItems: 'center',
        backgroundColor: colors.white,
        borderRadius: 16,
        paddingHorizontal: spacing.md,
        height: 50,
        borderWidth: 1,
        borderColor: colors.border,
    },
    searchInput: {
        fontFamily: typography.fontFamily.medium,
        flex: 1,
        marginLeft: spacing.sm,
        fontSize: typography.fontSize.sm,
        fontWeight: typography.fontWeight.bold,
        color: colors.textPrimary,
    },
    categoriesContainer: {
        paddingLeft: spacing.xl,
        marginBottom: spacing.lg,
    },
    categoryChip: {
        paddingHorizontal: 20,
        paddingVertical: 10,
        borderRadius: 16,
        marginRight: spacing.sm,
        borderWidth: 1,
        borderColor: colors.border,
        backgroundColor: colors.white,
    },
    categoryChipActive: {
        backgroundColor: colors.primary,
        borderColor: colors.primary,
    },
    categoryText: {
        fontFamily: typography.fontFamily.black,
        fontSize: 11,
        fontWeight: typography.fontWeight.black,
        color: colors.textSecondary,
        textTransform: 'uppercase',
        letterSpacing: 1,
    },
    categoryTextActive: {
        color: colors.white,
    },
    productsGrid: {
        paddingHorizontal: spacing.xl,
        flexDirection: 'row',
        flexWrap: 'wrap',
        justifyContent: 'space-between',
        paddingBottom: 100,
    },
    productCard: {
        width: width > 600 ? (width - (spacing.xl * 2) - 60) / 4 : (width - (spacing.xl * 2) - 15) / 2,
        backgroundColor: colors.white,
        borderRadius: 24,
        padding: 12,
        marginBottom: 15,
        borderWidth: 1,
        borderColor: colors.border,
        position: 'relative',
    },
    stockBadge: {
        position: 'absolute',
        top: 8,
        right: 8,
        zIndex: 10,
        backgroundColor: '#ef4444',
        paddingHorizontal: 6,
        paddingVertical: 2,
        borderRadius: 6,
    },
    stockBadgeText: {
        color: 'white',
        fontSize: 8,
        fontWeight: 'bold',
        textTransform: 'uppercase',
    },
    imagePlaceholder: {
        aspectRatio: 1,
        backgroundColor: colors.background,
        borderRadius: 18,
        justifyContent: 'center',
        alignItems: 'center',
        marginBottom: 10,
    },
    productInfo: {
        flex: 1,
    },
    productName: {
        fontFamily: typography.fontFamily.medium,
        fontSize: 13,
        fontWeight: typography.fontWeight.bold,
        color: colors.textPrimary,
        height: 32,
    },
    faltantesText: {
        color: '#ef4444',
        fontSize: 8,
        marginTop: 2,
        fontWeight: '700',
    },
    productPrice: {
        fontFamily: typography.fontFamily.bold,
        fontSize: 16,
        fontWeight: '900',
        color: colors.primary,
        marginTop: 4,
    },
    emptyContainer: {
        paddingTop: 60,
        alignItems: 'center',
        justifyContent: 'center',
    },
    emptyText: {
        fontFamily: typography.fontFamily.medium,
        marginTop: 10,
        fontSize: typography.fontSize.sm,
        fontWeight: typography.fontWeight.bold,
        color: colors.textMuted,
    },
    // Modal Styles
    modalOverlay: {
        flex: 1,
        backgroundColor: 'rgba(0,0,0,0.4)',
        justifyContent: 'flex-end',
    },
    modalContent: {
        backgroundColor: colors.white,
        borderTopLeftRadius: 32,
        borderTopRightRadius: 32,
        height: '85%',
        paddingTop: spacing.xl,
    },
    modalHeader: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        paddingHorizontal: spacing.xl,
        marginBottom: spacing.lg,
    },
    modalTitle: {
        fontFamily: typography.fontFamily.black,
        fontSize: typography.fontSize.xl,
        fontWeight: typography.fontWeight.black,
        color: colors.textPrimary,
    },
    modalSubtitle: {
        fontFamily: typography.fontFamily.black,
        fontSize: 10,
        fontWeight: typography.fontWeight.black,
        color: colors.textMuted,
        textTransform: 'uppercase',
        letterSpacing: 1.5,
    },
    carritoList: {
        paddingHorizontal: 20,
        paddingBottom: 40,
    },
    cartItem: {
        flexDirection: 'row',
        alignItems: 'center',
        backgroundColor: colors.surface,
        padding: 16,
        borderRadius: 24,
        marginBottom: 14,
        borderWidth: 1.5,
        borderColor: colors.border + '44',
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 4 },
        shadowOpacity: 0.05,
        shadowRadius: 10,
        elevation: 2,
    },
    cartItemImage: {
        width: 54,
        height: 54,
        borderRadius: 16,
        backgroundColor: colors.background,
        justifyContent: 'center',
        alignItems: 'center',
        marginRight: 14,
    },
    cartItemInfo: {
        flex: 1,
    },
    cartItemName: {
        fontSize: 15,
        fontWeight: '900',
        color: colors.textPrimary,
        letterSpacing: -0.3,
    },
    cartItemPrice: {
        fontSize: 13,
        fontWeight: '700',
        color: colors.primary,
        marginTop: 2,
    },
    quantityControls: {
        flexDirection: 'row',
        alignItems: 'center',
        backgroundColor: colors.background,
        borderRadius: 20,
        padding: 4,
        borderWidth: 1,
        borderColor: colors.border,
    },
    qtyBtn: {
        width: 32,
        height: 32,
        borderRadius: 16,
        backgroundColor: colors.surface,
        justifyContent: 'center',
        alignItems: 'center',
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.1,
        shadowRadius: 4,
        elevation: 2,
    },
    qtyText: {
        width: 30,
        textAlign: 'center',
        fontSize: 14,
        fontWeight: '900',
        color: colors.textPrimary,
    },
    checkoutFooter: {
        padding: 24,
        backgroundColor: colors.surface,
        borderTopLeftRadius: 32,
        borderTopRightRadius: 32,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: -10 },
        shadowOpacity: 0.05,
        shadowRadius: 15,
        elevation: 20,
        paddingBottom: Platform.OS === 'ios' ? 40 : 24,
    },
    formRow: {
        flexDirection: 'row',
        gap: 12,
        marginBottom: 24,
    },
    inputSmall: {
        flex: 1.5,
        backgroundColor: colors.background,
        borderRadius: 16,
        paddingHorizontal: 16,
        height: 52,
        borderWidth: 1.5,
        borderColor: colors.border,
        fontSize: 14,
        fontWeight: '700',
        color: colors.textPrimary,
    },
    selectSmall: {
        flex: 1,
        backgroundColor: colors.background,
        borderRadius: 16,
        justifyContent: 'center',
        paddingHorizontal: 12,
        height: 52,
        borderWidth: 1.5,
        borderColor: colors.border,
    },
    selectText: {
        fontSize: 13,
        fontWeight: '900',
        color: colors.textPrimary,
        textAlign: 'center',
    },
    totalRow: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'flex-end',
        marginBottom: 24,
    },
    totalLabel: {
        fontSize: 12,
        fontWeight: '900',
        color: colors.textMuted,
        textTransform: 'uppercase',
        letterSpacing: 1,
    },
    totalValue: {
        fontSize: 38,
        fontWeight: '900',
        color: colors.textPrimary,
        letterSpacing: -1.5,
    },
    confirmBtn: {
        backgroundColor: colors.primary,
        height: 64,
        borderRadius: 22,
        flexDirection: 'row',
        justifyContent: 'center',
        alignItems: 'center',
        gap: 10,
        shadowColor: colors.primary,
        shadowOffset: { width: 0, height: 8 },
        shadowOpacity: 0.3,
        shadowRadius: 15,
        elevation: 8,
    },
    confirmBtnText: {
        color: colors.white,
        fontSize: 18,
        fontWeight: '900',
    },
    metodoTag: {
        paddingVertical: 8,
        paddingHorizontal: 12,
        borderRadius: 12,
        borderWidth: 1,
        borderColor: colors.border,
        backgroundColor: colors.surface,
    },
    metodoTagText: {
        fontSize: 16,
        fontWeight: 'bold',
    }
});
