import { StyleSheet, Dimensions, Platform } from 'react-native';
import { colors, spacing, borderRadius, typography } from '../theme';

const { width, height } = Dimensions.get('window');

export const styles = StyleSheet.create({
    container: {
        flex: 1,
        backgroundColor: colors.background,
    },
    header: {
        paddingTop: Platform.OS === 'ios' ? 60 : 40,
        paddingHorizontal: spacing.xl,
        paddingBottom: spacing.md,
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
    },
    headerTitle: {
        fontFamily: typography.fontFamily.black,
        fontSize: typography.fontSize.xl,
        fontWeight: typography.fontWeight.black,
        color: colors.textPrimary,
        letterSpacing: -0.5,
    },
    cartButton: {
        width: 44,
        height: 44,
        borderRadius: 14,
        backgroundColor: colors.white,
        justifyContent: 'center',
        alignItems: 'center',
        borderWidth: 1,
        borderColor: colors.border,
        position: 'relative',
    },
    cartBadge: {
        position: 'absolute',
        top: -5,
        right: -5,
        minWidth: 20,
        height: 20,
        borderRadius: 10,
        backgroundColor: colors.primary,
        justifyContent: 'center',
        alignItems: 'center',
        borderWidth: 2,
        borderColor: colors.white,
    },
    cartBadgeText: {
        fontFamily: typography.fontFamily.black,
        color: colors.white,
        fontSize: 10,
        fontWeight: typography.fontWeight.black,
    },
    searchContainer: {
        paddingHorizontal: spacing.xl,
        marginBottom: spacing.md,
    },
    searchInputWrapper: {
        flexDirection: 'row',
        alignItems: 'center',
        backgroundColor: colors.white,
        borderRadius: 16,
        paddingHorizontal: spacing.md,
        height: 50,
        borderWidth: 1,
        borderColor: colors.border,
    },
    searchInput: {
        fontFamily: typography.fontFamily.medium,
        flex: 1,
        marginLeft: spacing.sm,
        fontSize: typography.fontSize.sm,
        fontWeight: typography.fontWeight.bold,
        color: colors.textPrimary,
    },
    categoriesContainer: {
        paddingLeft: spacing.xl,
        marginBottom: spacing.lg,
    },
    categoryChip: {
        paddingHorizontal: 20,
        paddingVertical: 10,
        borderRadius: 16,
        marginRight: spacing.sm,
        borderWidth: 1,
        borderColor: colors.border,
        backgroundColor: colors.white,
    },
    categoryChipActive: {
        backgroundColor: colors.primary,
        borderColor: colors.primary,
    },
    categoryText: {
        fontFamily: typography.fontFamily.black,
        fontSize: 11,
        fontWeight: typography.fontWeight.black,
        color: colors.textSecondary,
        textTransform: 'uppercase',
        letterSpacing: 1,
    },
    categoryTextActive: {
        color: colors.white,
    },
    productsGrid: {
        paddingHorizontal: spacing.xl,
        flexDirection: 'row',
        flexWrap: 'wrap',
        justifyContent: 'space-between',
        paddingBottom: 100,
    },
    productCard: {
        width: (width - (spacing.xl * 2) - 15) / 2,
        backgroundColor: colors.white,
        borderRadius: 24,
        padding: 12,
        marginBottom: 15,
        borderWidth: 1,
        borderColor: colors.border,
    },
    imagePlaceholder: {
        aspectRatio: 1,
        backgroundColor: colors.background,
        borderRadius: 18,
        justifyContent: 'center',
        alignItems: 'center',
        marginBottom: 10,
    },
    imageEmoji: {
        fontSize: 32,
    },
    productName: {
        fontFamily: typography.fontFamily.medium,
        fontSize: 13,
        fontWeight: typography.fontWeight.normal,
        color: colors.textPrimary,
        height: 32,
    },
    productPrice: {
        fontFamily: typography.fontFamily.bold,
        fontSize: 16,
        fontWeight: typography.fontWeight.medium,
        color: colors.primary,
        marginTop: 4,
    },
    emptyContainer: {
        paddingTop: 60,
        alignItems: 'center',
        justifyContent: 'center',
    },
    emptyText: {
        fontFamily: typography.fontFamily.medium,
        marginTop: 10,
        fontSize: typography.fontSize.sm,
        fontWeight: typography.fontWeight.bold,
        color: colors.textMuted,
    },
    // Modal Styles
    modalOverlay: {
        flex: 1,
        backgroundColor: 'rgba(0,0,0,0.4)',
        justifyContent: 'flex-end',
    },
    modalContent: {
        backgroundColor: colors.white,
        borderTopLeftRadius: 32,
        borderTopRightRadius: 32,
        height: '85%',
        paddingTop: spacing.xl,
    },
    modalHeader: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        paddingHorizontal: spacing.xl,
        marginBottom: spacing.lg,
    },
    modalTitle: {
        fontFamily: typography.fontFamily.black,
        fontSize: typography.fontSize.xl,
        fontWeight: typography.fontWeight.black,
        color: colors.textPrimary,
    },
    modalSubtitle: {
        fontFamily: typography.fontFamily.black,
        fontSize: 10,
        fontWeight: typography.fontWeight.black,
        color: colors.textMuted,
        textTransform: 'uppercase',
        letterSpacing: 1.5,
    },
    carritoList: {
        paddingHorizontal: spacing.xl,
    },
    cartItem: {
        flexDirection: 'row',
        alignItems: 'center',
        backgroundColor: colors.background,
        padding: 12,
        borderRadius: 20,
        marginBottom: 12,
        borderWidth: 1,
        borderColor: colors.border,
    },
    cartItemImage: {
        width: 48,
        height: 48,
        borderRadius: 12,
        backgroundColor: colors.white,
        justifyContent: 'center',
        alignItems: 'center',
        marginRight: 12,
    },
    cartItemInfo: {
        flex: 1,
    },
    cartItemName: {
        fontFamily: typography.fontFamily.medium,
        fontSize: 14,
        fontWeight: typography.fontWeight.normal,
        color: colors.textPrimary,
    },
    cartItemPrice: {
        fontFamily: typography.fontFamily.bold,
        fontSize: 12,
        fontWeight: typography.fontWeight.medium,
        color: colors.primary,
    },
    quantityControls: {
        flexDirection: 'row',
        alignItems: 'center',
        backgroundColor: colors.white,
        borderRadius: 12,
        borderWidth: 1,
        borderColor: colors.border,
        overflow: 'hidden',
    },
    qtyBtn: {
        width: 32,
        height: 32,
        justifyContent: 'center',
        alignItems: 'center',
    },
    qtyText: {
        fontFamily: typography.fontFamily.black,
        width: 24,
        textAlign: 'center',
        fontSize: 12,
        fontWeight: typography.fontWeight.black,
        color: colors.textPrimary,
    },
    checkoutFooter: {
        padding: spacing.xl,
        backgroundColor: colors.white,
        borderTopWidth: 1,
        borderTopColor: colors.border,
        paddingBottom: Platform.OS === 'ios' ? 40 : 20,
    },
    formRow: {
        flexDirection: 'row',
        gap: 10,
        marginBottom: 20,
    },
    inputSmall: {
        fontFamily: typography.fontFamily.medium,
        flex: 1.5,
        backgroundColor: colors.background,
        borderRadius: 12,
        paddingHorizontal: 15,
        height: 45,
        borderWidth: 1,
        borderColor: colors.border,
        fontSize: 12,
        fontWeight: 'bold',
    },
    selectSmall: {
        flex: 1,
        backgroundColor: colors.background,
        borderRadius: 12,
        justifyContent: 'center',
        paddingHorizontal: 10,
        height: 45,
        borderWidth: 1,
        borderColor: colors.border,
    },
    selectText: {
        fontFamily: typography.fontFamily.bold,
        fontSize: 12,
        fontWeight: 'bold',
        color: colors.textPrimary,
    },
    totalRow: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'flex-end',
        marginBottom: 20,
    },
    totalLabel: {
        fontFamily: typography.fontFamily.black,
        fontSize: 10,
        fontWeight: typography.fontWeight.black,
        color: colors.textMuted,
        textTransform: 'uppercase',
    },
    totalValue: {
        fontFamily: typography.fontFamily.black,
        fontSize: 32,
        fontWeight: typography.fontWeight.black,
        color: colors.textPrimary,
        letterSpacing: -1,
    },
    confirmBtn: {
        backgroundColor: colors.primary,
        height: 60,
        borderRadius: 20,
        flexDirection: 'row',
        justifyContent: 'center',
        alignItems: 'center',
        gap: 8,
        shadowColor: colors.primary,
        shadowOffset: { width: 0, height: 8 },
        shadowOpacity: 0.2,
        shadowRadius: 12,
        elevation: 5,
    },
    confirmBtnText: {
        fontFamily: typography.fontFamily.black,
        color: colors.white,
        fontSize: 16,
        fontWeight: typography.fontWeight.black,
    }
});
