import { StyleSheet, Dimensions, Platform } from 'react-native';

const { width, height } = Dimensions.get('window');
export const cardWidth = (width - 48 - 12) / 2; // xl spacing is usually 24, md is 12

export const createStyles = (colors: any) => StyleSheet.create({
    loadingContainer: {
        flex: 1,
        justifyContent: 'center',
        alignItems: 'center',
        backgroundColor: colors.background,
    },
    loadingText: {
        marginTop: 12,
        fontSize: 14,
        color: colors.textSecondary,
        fontWeight: '700',
    },
    container: {
        flex: 1,
        backgroundColor: colors.background,
    },
    scrollContent: {
        paddingVertical: 24,
    },
    greetingTitle: {
        fontSize: 12,
        fontWeight: '900',
        color: colors.textMuted,
        textTransform: 'uppercase',
        letterSpacing: 1.5,
        paddingHorizontal: 24,
        marginBottom: 4,
    },
    greetingSubtitle: {
        fontSize: 28,
        fontWeight: '900',
        color: colors.textPrimary,
        paddingHorizontal: 24,
        letterSpacing: -1,
        marginBottom: 24,
    },
    content: {
        paddingHorizontal: 24,
        paddingBottom: 40,
    },
    glassCardBase: {
        borderRadius: 24,
        padding: 24,
        marginBottom: 16,
        backgroundColor: colors.card,
        borderWidth: 1,
        borderColor: colors.border,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 4 },
        shadowOpacity: 0.03,
        shadowRadius: 10,
        elevation: 1,
    },
    cardHeaderRow: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        marginBottom: 16,
    },
    glassIconContainerPrimary: {
        width: 52,
        height: 52,
        borderRadius: 16,
        backgroundColor: 'rgba(225, 29, 72, 0.1)',
        justifyContent: 'center',
        alignItems: 'center',
    },
    datePill: {
        paddingHorizontal: 12,
        paddingVertical: 6,
        backgroundColor: colors.background,
        borderRadius: 20,
        borderWidth: 1,
        borderColor: colors.border,
    },
    datePillText: {
        fontSize: 10,
        fontWeight: '900',
        color: colors.textSecondary,
        textTransform: 'uppercase',
    },
    cardLabel: {
        fontSize: 11,
        fontWeight: '900',
        color: colors.textSecondary,
        textTransform: 'uppercase',
        letterSpacing: 1.5,
        marginBottom: 4,
    },
    cardValue: {
        fontSize: 40,
        fontWeight: '900',
        color: colors.textPrimary,
        letterSpacing: -2,
    },
    cardSubtitle: {
        fontSize: 12,
        fontWeight: '500',
        color: colors.textMuted,
        marginTop: 4,
    },
    statsGrid: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        marginBottom: 20,
    },
    glassCardGrid: {
        borderRadius: 20,
        padding: 16,
        borderWidth: 1,
        borderColor: colors.border,
        backgroundColor: colors.card,
        flexDirection: 'column',
        justifyContent: 'space-between',
        height: 145,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 4 },
        shadowOpacity: 0.03,
        shadowRadius: 10,
        elevation: 1,
    },
    glassIconContainerSecondary: {
        width: 40,
        height: 40,
        borderRadius: 12,
        backgroundColor: 'rgba(59, 130, 246, 0.1)',
        justifyContent: 'center',
        alignItems: 'center',
        marginBottom: 8,
    },
    glassIconContainerWarning: {
        width: 40,
        height: 40,
        borderRadius: 12,
        backgroundColor: 'rgba(245, 158, 11, 0.1)',
        justifyContent: 'center',
        alignItems: 'center',
        marginBottom: 8,
    },
    gridCardLabel: {
        fontSize: 10,
        fontWeight: '900',
        color: colors.textSecondary,
        textTransform: 'uppercase',
        letterSpacing: 1,
    },
    gridCardValue: {
        fontSize: 20,
        fontWeight: '900',
        color: colors.textPrimary,
        letterSpacing: -1,
    },
    gridCardSubtitle: {
        fontSize: 10,
        fontWeight: '500',
        color: colors.textMuted,
    },
    glassSection: {
        borderRadius: 24,
        borderWidth: 1,
        borderColor: colors.border,
        backgroundColor: colors.card,
        marginBottom: 20,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 4 },
        shadowOpacity: 0.03,
        shadowRadius: 10,
        elevation: 1,
        overflow: 'hidden', // Asegura que los bordes redondeados corten el contenido
    },
    sectionHeader: {
        flexDirection: 'row',
        alignItems: 'center',
        paddingHorizontal: 20,
        paddingVertical: 16,
        borderBottomWidth: 1,
        borderBottomColor: colors.border,
        backgroundColor: colors.card, // Fondo sólido para la cabecera
    },
    glassIconSmall: {
        width: 32,
        height: 32,
        borderRadius: 10,
        backgroundColor: colors.background,
        justifyContent: 'center',
        alignItems: 'center',
    },
    sectionTitle: {
        fontSize: 14,
        fontWeight: '900',
        color: colors.textPrimary,
        marginLeft: 8,
    },
    listContainer: {
        paddingHorizontal: 12,
        paddingBottom: 12,
    },
    glassListItem: {
        flexDirection: 'row',
        alignItems: 'center',
        paddingVertical: 12,
        borderBottomWidth: StyleSheet.hairlineWidth,
        borderBottomColor: colors.border,
    },
    listItemRank: {
        width: 36,
        height: 36,
        backgroundColor: 'rgba(0,0,0,0.03)',
        borderRadius: 10,
        justifyContent: 'center',
        alignItems: 'center',
        marginRight: 12,
    },
    listItemRankText: {
        fontSize: 16,
        fontWeight: '900',
        color: colors.textPrimary,
    },
    listItemInfo: {
        flex: 1,
    },
    listItemTitle: {
        fontSize: 14,
        fontWeight: '600',
        color: colors.textPrimary,
    },
    listItemSubtitle: {
        fontSize: 12,
        color: colors.textMuted,
        marginTop: 2,
    },
    listItemRightBadge: {
        backgroundColor: 'rgba(225, 29, 72, 0.1)',
        paddingHorizontal: 12,
        paddingVertical: 6,
        borderRadius: 20,
    },
    listItemRightBadgeText: {
        fontSize: 12,
        fontWeight: '900',
        color: colors.primary,
    },
    modalOverlay: {
        flex: 1,
        backgroundColor: 'rgba(0,0,0,0.5)',
        justifyContent: 'flex-end',
    },
    notificationModal: {
        borderTopLeftRadius: 32,
        borderTopRightRadius: 32,
        paddingTop: 24,
        paddingHorizontal: 24,
        paddingBottom: Platform.OS === 'ios' ? 40 : 20,
        maxHeight: height * 0.8,
    },
    modalHeader: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        marginBottom: 24,
    },
    modalTitle: {
        fontSize: 20,
        fontWeight: '900',
        color: colors.textPrimary,
    },
    emptyText: {
        padding: 24,
        textAlign: 'center',
        color: colors.textMuted,
        fontSize: 14,
    },
    // Nuevos estilos para Financial Health
    financialRow: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
    },
    financialIndicator: {
        alignItems: 'center',
        flex: 1,
    },
    indicatorLabel: {
        fontSize: 9,
        color: colors.textMuted,
        textTransform: 'uppercase',
        marginBottom: 2,
    },
    indicatorValue: {
        fontSize: 14,
        fontWeight: '800',
        color: colors.textPrimary,
    },
    indicatorValuePositive: {
        fontSize: 14,
        fontWeight: '800',
        color: '#10b981',
    },
    indicatorValuePrimary: {
        fontSize: 14,
        fontWeight: '800',
        color: colors.primary,
    },
    divider: {
        width: 1,
        height: '100%',
        backgroundColor: colors.border,
    },
    growthBadge: {
        paddingHorizontal: 4,
        paddingVertical: 1,
        borderRadius: 4,
        marginLeft: 4,
    },
    growthText: {
        fontSize: 8,
        fontWeight: 'bold',
        color: 'white',
    }
});
